Add sample app
quarkiverse/quarkus-json-rpc pull request #2
Opened 2024-07-17 06:49 UTC by tecarter94

Added sample app for manual testing. Performed refactoring to get things working.

2024-07-17 06:58 UTC, phillip-kruger commented on runtime/pom.xml
> +            <version>2.17.2</version>
The version should be driven from quarkus bom (I think)

2024-07-17 07:07 UTC, phillip-kruger requested changes
One small comment w.r.t Jackson version in the pom

2024-07-18 00:12 UTC, tecarter94 commented on runtime/pom.xml
> +            <version>2.17.2</version>
You're right! Corrected.

2024-07-18 00:17 UTC, phillip-kruger approved these changes

2024-07-18 00:18 UTC, merged